set(DEFAULT_INSTALL_PATH /Library/Application Support/kicad)
set(OCC_INCLUDE_DIR /opt/homebrew/Cellar/opencascade/7.9.2/include/opencascade)
set(OCC_LIBRARY_DIR /opt/homebrew/Cellar/opencascade/7.9.2/lib)
set(CMAKE_INSTALL_PREFIX /Users/jeffallo/Documents/main_projects/trace/trace-mac-builder/build/kicad-dest)
set(CMAKE_C_COMPILER /usr/bin/clang)
set(CMAKE_CXX_COMPILER /usr/bin/clang++)
set(CMAKE_OSX_DEPLOYMENT_TARGET 12.0)
set(wxWidgets_CONFIG_EXECUTABLE /Users/jeffallo/Documents/main_projects/trace/trace-mac-builder/build/wxwidgets-dest/bin/wx-config)
set(KICAD_BUILD_I18N ON)
set(KICAD_SCRIPTING_WXPYTHON ON)
set(PYTHON_EXECUTABLE /Users/jeffallo/Documents/main_projects/trace/trace-mac-builder/build/python-dest/Library/Frameworks/Python.framework/Versions/Current/bin/python3)
set(PYTHON_INCLUDE_DIR /Users/jeffallo/Documents/main_projects/trace/trace-mac-builder/build/python-dest/Library/Frameworks/Python.framework/Versions/Current/include/python3.9/)
set(PYTHON_LIBRARY /Users/jeffallo/Documents/main_projects/trace/trace-mac-builder/build/python-dest/Library/Frameworks/Python.framework/Versions/Current/lib/libpython3.9.dylib)
set(PYTHON_SITE_PACKAGE_PATH /Users/jeffallo/Documents/main_projects/trace/trace-mac-builder/build/python-dest/Library/Frameworks/Python.framework/Versions/Current/lib/python3.9/site-packages)
set(PYTHON_FRAMEWORK /Users/jeffallo/Documents/main_projects/trace/trace-mac-builder/build/python-dest/Library/Frameworks/Python.framework)
set(NGSPICE_INCLUDE_DIR /Users/jeffallo/Documents/main_projects/trace/trace-mac-builder/build/ngspice-dest/include)
set(NGSPICE_LIBRARY /Users/jeffallo/Documents/main_projects/trace/trace-mac-builder/build/ngspice-dest/lib/libngspice.dylib)
set(AMPLITUDE_API_KEY )
